# testing options

option('lak_enable_tests',
	type: 'boolean',
	value: true,
	yield: true,
)

option('lak_enable_examples',
	type: 'boolean',
	value: false,
	yield: true,
)

option('lak_bounds_checks',
	type: 'combo',
	choices: [
		'always',
		'never',
		'debug',
	],
	value: 'always',
	yield: true,
)

# windowing options

option('lak_enable_windowing',
	type: 'boolean',
	value: true,
	yield: true,
)

option('lak_use_native_file_dialog',
	type: 'boolean',
	value: true,
	yield: true,
)

option('lak_run_windowing_tests',
	type: 'boolean',
	value: false,
	yield: true,
)

option('sdl2_from_source',
	type: 'boolean',
	value: true,
	yield: true,
)

option('lak_backend',
  type: 'combo',
  choices: [
    'win32',
    'xlib',
    'xcb',
    'sdl',
  ],
  value: 'sdl',
  yield: false,
)

option('lak_enable_softrender',
	type: 'boolean',
	value: true,
	yield: true,
)

option('lak_enable_opengl',
	type: 'boolean',
	value: true,
	yield: true,
)

option('lak_enable_cobalt',
	type: 'boolean',
	value: false,
	yield: true,
)

# llvm options

option('lak_enable_llvm',
  type: 'boolean',
  value: false,
  yield: false,
)

# lmdb options

option('lak_enable_lmdb',
	type: 'boolean',
	value: true,
	yield: true,
)

# lua options

option('lak_enable_lua',
	type: 'boolean',
	value: false,
	yield: true,
)

# glm options

option('lak_enable_glm',
	type: 'boolean',
	value: true,
	yield: true,
)

# dear imgui options

option('lak_enable_imgui',
	type: 'boolean',
	value: true,
	yield: true,
)

# libfive options

option('lak_enable_libfive',
	type: 'boolean',
	value: false,
	yield: true,
)

# libgphoto2 options

option('lak_enable_libgphoto2',
	type: 'boolean',
	value: false,
	yield: true,
)

# openvr options

option('lak_enable_openvr',
	type: 'boolean',
	value: false,
	yield: true,
)

# stb options

option('lak_enable_stb',
	type: 'boolean',
	value: true,
	yield: true,
)

option('lak_enable_stb_image',
	type: 'boolean',
	value: true,
	yield: true,
)

option('lak_enable_stb_image_write',
	type: 'boolean',
	value: true,
	yield: true,
)

# godot-cpp options

option('lak_enable_godot_cpp',
	type: 'boolean',
	value: false,
	yield: true,
)
