name: Build

on:
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]
  workflow_dispatch:

jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022, ubuntu-24.04, macos-15]
        arch: [x86, x64, arm64]
        target:
          - srcexp
        exclude:
          - os: windows-2022
            arch: arm64
          - os: ubuntu-24.04
            arch: arm64
          - os: macos-15
            arch: x86
          - os: macos-15
            arch: x64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12.x'

      - if: startsWith(matrix.os, 'windows')
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}
          vsversion: 2022
      - if: startsWith(matrix.os, 'windows')
        run: |
          python3 -m pip install --upgrade pip setuptools wheel
          python3 -m pip install meson ninja

      - if: startsWith(matrix.os, 'ubuntu')
        uses: egor-tensin/setup-gcc@v1
        with:
          version: 13
          platform: ${{ matrix.arch }}
      - if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo python3 -m pip install --upgrade setuptools
          sudo python3 -m pip install meson ninja

      - if: startsWith(matrix.os, 'macos')
        run: |
          brew install meson ninja
          echo "CC=$(brew --prefix llvm@18)/bin/clang" >> $GITHUB_ENV
          echo "CXX=$(brew --prefix llvm@18)/bin/clang++" >> $GITHUB_ENV

        # _DISABLE_CONSTEXPR_MUTEX_CONSTRUCTOR is a hack fix for https://github.com/actions/runner-images/issues/10004
      - run: meson setup build -Dcpp_args="-D_DISABLE_CONSTEXPR_MUTEX_CONSTRUCTOR" --buildtype debugoptimized
      - run: meson compile -C build ${{ matrix.target }}
      # - run: run tests
  push-staging:
    needs: run-tests
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Push staging branch to trunk
        if: github.event_name == 'push'
        run: git switch trunk && git merge --ff-only staging && git push origin trunk
